manifest:
  remotes:
    - name: EmpWorks
      url-base: https://github.com/EmpWorks
  projects:
    - name: zmk-lpm009m360a-driver
      remote: EmpWorks
      revision: master
      import: app/west.yml
  self:
    path: config
